# Generated by Django 5.2 on 2026-01-29 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "idioma",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decks",
                        to="accounts.idioma",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_origem", models.TextField()),
                ("texto_alvo", models.TextField()),
                ("url_imagem", models.URLField(blank=True, null=True)),
                ("url_audio", models.URLField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("basic", "Básico (frente/verso)"),
                            ("translation", "Tradução com imagem"),
                            ("sentence", "Frase"),
                            ("dialog", "Diálogo"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcards",
                        to="study.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ReviewHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avaliacao",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Again"), (2, "Hard"), (3, "Good"), (4, "Easy")]
                    ),
                ),
                ("data_revisao", models.DateTimeField(auto_now_add=True)),
                (
                    "estabilidade_antes",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estabilidade_depois",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "dificuldade_antes",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "dificuldade_depois",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("intervalo_dias", models.PositiveIntegerField()),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="study.flashcard",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisao"],
            },
        ),
        migrations.CreateModel(
            name="CardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dificuldade",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "estabilidade",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=10),
                ),
                ("data_vencimento", models.DateField()),
                ("data_ultima_revisao", models.DateField(blank=True, null=True)),
                (
                    "recuperabilidade",
                    models.DecimalField(decimal_places=3, default=0.9, max_digits=5),
                ),
                ("parametros", models.JSONField(default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estados",
                        to="study.flashcard",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["data_vencimento"],
                        name="study_cards_data_ve_fa71a4_idx",
                    )
                ],
                "unique_together": {("flashcard", "usuario")},
            },
        ),
    ]
