# Generated by Django 5.2 on 2026-01-30 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardstate",
            name="data_ultima_revisao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cardstate",
            name="data_vencimento",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="cardstate",
            name="dificuldade",
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name="cardstate",
            name="estabilidade",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="cardstate",
            name="recuperabilidade",
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="dificuldade_antes",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="dificuldade_depois",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="estabilidade_antes",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="reviewhistory",
            name="estabilidade_depois",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="FsrsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weights", models.JSONField()),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
